### ISSUE TITLE
Stack name doesn't fit naming requirements

### ISSUE THREAD

**Issue by mjdinsmore** [datasprayio/aws-cdk-maven-plugin#69]
When deploying my stack (it synths fine), I get an error like:

`[ERROR] Failed to execute goal io.dataspray:aws-cdk-maven-plugin:2.1.3:deploy (deploy-cdk-app) on project thiscdk: 1 validation error detected: Value 'StackForThis-RESEARCH-dev (ThisStack-RESEARCH-dev)' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]* (Service: CloudFormation, Status Code: 400, Request ID: 7c3db1cd-adab-4c71-8018-2c291d82663c) -> [Help 1]`

I set that stack name to "StackForThis-RESEARCH-dev" in the code.  This has been deploying fine previously with the linguarobot and ealier versions of the plugin.  Was there a change recently to the code -- requiring me to name the stack in the Maven pom.xml file?    A stack name can most certainly have dashes/hyphens ("-") in it.  The "StackForThis-RESEARCH-dev" is my id, while "ThisStack-RESEARCH-dev" is the name.

Thank you.

**Comment by matusfaro** [comment]
That's strange because `StackForThis-RESEARCH-dev` matches the regex `[a-zA-Z][-a-zA-Z0-9]*`. Is the error message exactly copied or did you modify it?

Also could you show the relevant code around this? it's hard to determine where the `stackName` is set. Possibly you could show the cloudformation template where the stackname is used?

There were significant changes from LinguaRobot as AWS CDK changed quite a lot. I can't think of which particular change caused this, but hopefully if you provide more details I can help you.

**Comment by matusfaro** [comment]
Ah the stack name is exactly `StackForThis-RESEARCH-dev (ThisStack-RESEARCH-dev)` including the spaces and brackets. Please remove the spaces and brackets, dashes are fine.

**Comment by mjdinsmore** [comment]
I was getting the impression the displayed stack name was part of the output string your tool was generating.  My code for getting the stack name is simple:

`    public static String getStackName() {
        return String.format("%s-%s-%s", STACK_NAME, getEnvironment().getContext(),
               getEnvironment().getTier();
    }
`

whereas the context and tier are supplied variables at compile time (i.e dev,qa,prod, etc.).  And then it's a simple one-liner to create the stack (which calls that getStackName method):

`final MyCdkStack myCdkStack = new MyCdkStack(myApp, getStackName(), getStackProps());`

**Comment by matusfaro** [comment]
Can you dig a little deeper into `MyCdkStack`, where do you pass in the stack name into?

**Comment by matusfaro** [comment]
Also, could you look into the output of `getEnvironment().getTier()`? Whether it prints out just `dev` or maybe it prints out `dev (ThisStack-RESEARCH-dev)`?

**Comment by matusfaro** [comment]
The error your specified is an error from CloudFormation itself, not a constraint of this tool. This means that the synthesized cloudformation output already contains this incorrect stack name. (You can also verify this by searching for it inside `target/cdk.out` folder) How it gets constructed is what we're looking to find and whether it's constructed incorrectly on your side or the tool's side. If it's the tool side, I need to know more information where to look because I couldn't find any place where we append a name with brackets.

**Comment by matusfaro** [comment]
I assume you found the issue on your side, please re-open if you have any more questions.
